test_that("tables reject invalid values before plotting", {
  good <- data.frame(x = c(1, 2), y = c(2, 3), cell_type = c("B", "T"))
  expect_error(plot_embedding_panel(list()), "data frame")
  expect_error(plot_embedding_panel(good[FALSE, ]), "at least one row")
  bad <- good; bad$x[1] <- Inf
  expect_error(plot_embedding_panel(bad), "finite numeric")
  bad <- good; bad$x <- as.character(bad$x)
  expect_error(plot_embedding_panel(bad), "finite numeric")
  bad <- good; bad$cell_type[1] <- " "
  expect_error(plot_embedding_panel(bad), "blank")
  expect_error(plot_embedding_panel(good, alpha = 2), "alpha")
  expect_error(plot_embedding_panel(good, category_order = "B"), "category_order")
  p <- plot_embedding_panel(good, label = TRUE, category_order = c("T", "B"))
  expect_identical(levels(p$data$cell_type), c("T", "B"))
  expect_no_error(ggplot2::ggplotGrob(p))
})

test_that("palettes have unique names, valid colors, and full category coverage", {
  expect_error(validate_palette("B", c(B = "not-a-color")), "invalid color")
  expect_error(validate_palette("B", stats::setNames(c("red", "blue"), c("B", "B"))), "unique")
  expect_error(read_nc_palette(data.frame(cell_type = c("B", "B"), color = c("red", "blue"))), "unique")
  expect_error(validate_palette(c("B", NA), c(B = "red")), "missing")
  expect_error(validate_palette("B", NULL), "NULL")
})

test_that("composition preserves fractions and distinguishes counts", {
  data <- data.frame(group = c("sample", "sample"), cell_type = c("B", "T"), proportion = c(.3, .7))
  expect_no_error(ggplot2::ggplotGrob(plot_composition_panel(data)))
  expect_error(plot_composition_panel(rbind(data, data[1, ])), "duplicate")
  bad <- data; bad$proportion <- c(-.1, 1.1)
  expect_error(plot_composition_panel(bad), "non-negative")
  bad <- data; bad$proportion <- c(.2, .2)
  expect_error(plot_composition_panel(bad), "sum to 1")
  expect_no_error(ggplot2::ggplot_build(plot_composition_panel(bad, position = "stack")))
  data$n <- c(3, 7)
  counts <- plot_composition_panel(data, value_col = "n", value_type = "count", position = "stack")
  expect_identical(counts$scales$get_scales("y")$labels(3), "3")
  expect_no_error(ggplot2::ggplotGrob(counts))
})

test_that("custom tags are applied and invalid panels rejected", {
  p <- ggplot2::ggplot(data.frame(x = 1, y = 1), ggplot2::aes(x, y)) + ggplot2::geom_point()
  custom <- compose_nc_figure(list(p, p), labels = c("a", "b"))
  expect_identical(custom$patches$annotation$tag_levels, list(c("a", "b")))
  expect_no_error(patchwork::patchworkGrob(custom))
  expect_null(compose_nc_figure(list(p), labels = NULL)$patches$annotation$tag_levels)
  expect_error(compose_nc_figure(list(p, "bad")), "every panel")
  expect_error(compose_nc_figure(list(p, p), labels = "a"), "one unique label")
  expect_error(compose_nc_figure(list(p), ncol = 0), "positive integer")
  layout <- compose_nc_figure(list(A = p, B = p), design = "AB", widths = c(2, 1), heights = 1, guides = "collect")
  expect_identical(layout$patches$layout$widths, c(2, 1))
  expect_identical(layout$patches$layout$guides, "collect")
  expect_no_error(patchwork::patchworkGrob(layout))
  expect_error(compose_nc_figure(list(p), widths = c(1, 0)), "positive finite")
  expect_error(compose_nc_figure(list(p), heights = NA_real_), "positive finite")
})

test_that("export failures close devices and preserve existing bundles", {
  p <- ggplot2::ggplot(data.frame(x = 1, y = 1), ggplot2::aes(x, y)) + ggplot2::geom_point()
  out <- tempfile(); dir.create(out)
  paths <- export_figure_bundle(p, "figure", out, width = 2, height = 2,
    source_manifest = data.frame(source = "synthetic"))
  expect_true(all(file.info(unlist(paths))$size > 0))
  expect_true(any(grepl("R version", readLines(paths$session))))
  hashes <- tools::md5sum(unlist(paths))
  before <- grDevices::dev.cur()
  bad <- ggplot2::ggplot(data.frame(x = 1), ggplot2::aes(x, absent)) + ggplot2::geom_point()
  expect_error(export_figure_bundle(bad, "figure", out), "absent")
  expect_identical(grDevices::dev.cur(), before)
  expect_identical(tools::md5sum(unlist(paths)), hashes)
  expect_false(any(grepl("^\\.ncfigR-", list.files(out, all.files = TRUE))))
  expect_error(export_figure_bundle(p, "figure", out, overwrite = FALSE), "already exist")
  expect_error(export_figure_bundle(p, "../bad", out), "path separators")
  expect_error(export_figure_bundle(p, "figure", out, width = 0), "positive finite")
  export_figure_bundle(p, "figure", out, width = 2, height = 2)
  expect_false(file.exists(paths$manifest))
})

test_that("Seurat extraction rejects unknown genes and retains cell identity", {
  skip_if_not_installed("SeuratObject")
  counts <- matrix(c(1, 0, 2, 3, 1, 0), nrow = 2,
    dimnames = list(c("CD3D", "MS4A1"), c("feature", "c2", "c3")))
  object <- suppressWarnings(SeuratObject::CreateSeuratObject(counts))
  metadata <- as_panel_data(object, "metadata")
  expect_identical(metadata$cell_id, colnames(object))
  coordinates <- matrix(seq_len(6), nrow = 3,
    dimnames = list(colnames(object), c("UMAP_1", "UMAP_2")))
  object[["umap"]] <- SeuratObject::CreateDimReducObject(coordinates, key = "UMAP_", assay = "RNA")
  embedding <- as_panel_data(object, "embedding")
  expect_identical(embedding$cell_id, colnames(object))
  expect_equal(embedding$x, coordinates[, 1], ignore_attr = TRUE)
  expression <- as_panel_data(object, "expression", features = "CD3D", layer = "counts")
  expect_equal(nrow(expression), 3)
  expect_setequal(expression$cell_id, colnames(object))
  expect_error(as_panel_data(object, "expression", features = "missing", layer = "counts"), "not found")
  expect_error(as_panel_data(object, "expression", features = character()), "non-empty")
})
